using System.Collections.Generic;

namespace FracturedChorus.Narrative.Vn
{
    public static class VnLineCatalog
    {
        private static readonly Dictionary<string, string> Vi = new Dictionary<string, string>
        {
            { "LUMINA", "LUMINA" },
            { "This story is a work of fiction.", "Câu chuyện này là hư cấu." },
            { "Music is not decoration. It is the oldest language we never agreed to forget.", "Nhạc không phải đồ trang trí. Đó là thứ ngôn ngữ cổ nhất mà ta chưa bao giờ chịu quên." },
            { "Before words named the world, rhythm named what could not be named.", "Trước khi lời đặt tên cho thế giới, nhịp đã gọi tên những thứ không gọi được." },
            { "Every note carries a memory of something that once trembled in the dark—and chose to become sound.", "Mỗi nốt mang ký ức của một thứ từng run trong bóng tối — rồi chọn trở thành âm thanh." },
            { "They have learned to bend melody until it obeys.", "Họ đã học cách bẻ giai điệu cho đến khi nó chịu nghe lời." },
            { "Charts, contracts, silence where a chorus should rise—music reduced to a lever in someone else's hand.", "Bảng xếp hạng, hợp đồng, im lặng ở chỗ hợp xướng đáng lẽ phải vang — nhạc bị rút thành một cần gạt trong tay người khác." },
            { "They call it curation. They call it order. They call it progress.", "Họ gọi đó là tuyển chọn. Họ gọi đó là trật tự. Họ gọi đó là tiến bộ." },
            { "But music was never born to serve a master.", "Nhưng nhạc chưa bao giờ sinh ra để phục vụ một chủ nhân." },
            { "Strip away every market, every gate, every polished lie—and the pulse remains.", "Gạt hết chợ, hết cổng, hết lời nói dối được đánh bóng — nhịp vẫn còn." },
            { "You cannot own what lives inside the listener. You can only try to drown it out.", "Bạn không sở hữu được thứ sống trong người nghe. Bạn chỉ có thể cố át nó đi." },
            { "This is a journey back to the source—the place where every melody, however small, must be honored.", "Đây là đường về nguồn — nơi mỗi giai điệu, dù nhỏ, đều phải được trân trọng." },
            { "The path ahead is cruel: fractured roads, broken cadences, trials that will test everything you believe about sound.", "Đường phía trước rất độc: những lối nứt, những nhịp gãy, những thử thách sẽ soi mọi thứ bạn tin về âm thanh." },
            { "Only those who have agreed to the above\nhave the privilege of partaking in this game.", "Chỉ ai đã đồng ý những điều trên\nmới được bước vào trò chơi này." },
            { "I agree", "Tôi đồng ý" },
            { "I do not agree", "Tôi không đồng ý" },
            { "Perhaps you are not ready yet—we will wait for you.", "Có lẽ bạn chưa sẵn sàng — chúng tôi sẽ đợi." },
            { "The cadence does not hurry those who still need silence.", "Nhịp không thúc ai còn cần yên lặng." },
            { "We will keep your place at the threshold until you choose to listen again.", "Chỗ của bạn vẫn ở ngưỡng cửa, đến khi bạn muốn nghe lại." },
            { "Return when the melody calls to you. We will be here.", "Khi giai điệu gọi, hãy quay lại. Chúng tôi vẫn ở đây." },
            { "Thank you, {0}. The cadence remembers your name.\nMay your melody find its way home.", "Cảm ơn {0}. Nhịp đã nhớ tên bạn.\nChúc giai điệu của bạn tìm được đường về." },
            { "Morning in Lumina.\nA city that never walks out of time.", "Buổi sáng ở Lumina.\nThành phố này chẳng bao giờ bước ra khỏi thời gian." },
            { "Banners sell the same promise on every corner:\nmusic will make you whole.", "Biểu ngữ ở mọi góc phố bán cùng một lời hứa:\nnhạc sẽ khiến bạn trở nên trọn vẹn." },
            { "StellaWorks built the towers, the charts,\nand the device in every ear.", "StellaWorks dựng những tòa tháp, bảng xếp hạng,\nvà thiết bị trong mỗi tai." },
            { "If a song hits number one, the city hears it.\nThat is policy, not poetry.", "Bài hát lên số một thì cả thành phố phải nghe.\nĐó là chính sách, không phải thơ." },
            { "SyncPod SP-01. Clip on. Live in sync.\nBlue light: you are still yourself.", "SyncPod SP-01. Kẹp vào. Sống trong nhịp.\nĐèn xanh: bạn vẫn là chính mình." },
            { "HIMA Music Academy —\nwhere the city forges its next voices.", "Học viện Âm nhạc HIMA —\nnơi thành phố luyện những giọng hát tiếp theo." },
            { "Talent enters.\nThe charts decide who leaves famous.", "Tài năng bước vào.\nBảng xếp hạng quyết định ai ra về trong tiếng tăm." },
            { "Practice halls. Recital nights.\nA brighter tomorrow, printed on the walls.", "Phòng tập. Đêm độc tấu.\nMột ngày mai sáng hơn, in trên tường." },
            { "Evening. Somewhere in the city, a screen stays on.", "Tối. Một nơi nào đó trong thành phố, màn hình vẫn sáng." },
            { "Multiple SyncPod-related incidents.\nVictims found emptied — as if something drank them dry.", "Nhiều vụ liên quan SyncPod.\nNạn nhân bị rút cạn — như có thứ đã uống khô họ." },
            { "Authorities urge calm. No confirmed cause.\nThe ticker keeps moving.", "Chính quyền kêu gọi bình tĩnh. Chưa rõ nguyên nhân.\nDòng tin vẫn chạy." },
            { "LUMINA, 17 AUGUST 20XX", "LUMINA, 17 THÁNG 8 NĂM 20XX" },
            { "Under the lights of Astra Arena,\nLUXE holds the city in one chorus.", "Dưới đèn Astra Arena,\nLUXE giữ cả thành phố trong một hợp xướng." },
            { "The crowd detonates — lightsticks surge, a thousand voices roar the hook.", "Đám đông bùng nổ — lightstick dâng lên, nghìn giọng gầm điệp khúc." },
            { "Thank you, Lumina!\nWe'll carry this spark to the next stage!", "Cảm ơn Lumina!\nChúng tôi sẽ mang tia lửa này sang sân khấu sau!" },
            { "Stay with us. Eternal Spark — forever!", "Ở lại với chúng tôi. Eternal Spark — mãi mãi!" },
            { "The broadcast cuts. The street waits.", "Tín hiệu cắt. Phố vẫn chờ." },
            { "AT NEON CROSSING, LUMINA CITY", "NGÃ TƯ NEON, THÀNH PHỐ LUMINA" },
            { "Late night in Lumina.\nA city that never sleeps.", "Khuya ở Lumina.\nThành phố không ngủ." },
            { "On the giant screens, Prime Unit MVs loop again and again — no one remembers how many times.\nPeople pass by humming along, almost unconscious.", "Trên màn hình khổng lồ, MV Prime Unit lặp đi lặp lại — không ai nhớ đã bao nhiêu lần.\nNgười ta đi ngang và ngân nga, gần như vô thức." },
            { "…Another late shift. I’m wiped.", "…Lại ca khuya. Mình kiệt sức rồi." },
            { "SyncPod on his right ear. Blue LED. Slow pulse.\nPersonal playlist — track three: Bring Me Home.", "SyncPod ở tai phải. LED xanh. Nhịp chậm.\nPlaylist riêng — bài ba: Bring Me Home." },
            { "Bring Me Home… Yeah. That fits.", "Bring Me Home… Ừ. Hợp lúc này." },
            { "A line of the hit bleeds in through his left ear.\nHaruto shakes his head — his SyncPod stays on his own track.", "Một câu của bài hit lọt vào tai trái.\nHaruto lắc đầu — SyncPod của anh vẫn giữ bài của mình." },
            { "Not now.", "Không phải lúc này." },
            { "—!", "—!" },
            { "The LED on his ear flickers. Once. Twice.", "LED trên tai nhấp nháy. Một lần. Hai lần." },
            { "What the…? Why did it change tracks on its own?", "Cái gì…? Sao nó tự đổi bài?" },
            { "It hurts. What is this?", "Đau. Cái gì đây?" },
            { "Not the song he was listening to.\nNot the song on the billboard.\nSomething else — like a thousand needles driven into the heart.", "Không phải bài anh đang nghe.\nKhông phải bài trên biển quảng cáo.\nThứ khác — như nghìn mũi kim đâm vào tim." },
            { "Stop…! I have to shut it off!", "Dừng lại…! Mình phải tắt nó!" },
            { "The SyncPod doesn’t answer. His feet keep moving.\nNot toward home.", "SyncPod không đáp. Chân anh vẫn bước.\nKhông phải về nhà." },
            { "No… don’t…", "Không… đừng…" },
            { "Vision blurs. His body feels heavy — pulled forward on an invisible wire.\nHe slips through the crowd. No one notices.", "Mắt mờ. Người nặng — một sợi dây vô hình kéo anh về phía trước.\nAnh lách qua đám đông. Không ai để ý." },
            { "Lotus Service Lane — no billboards here.\nOnly emergency lights and the damp breath of shop ACs.", "Hẻm Dịch vụ Lotus — không biển quảng cáo.\nChỉ đèn khẩn và hơi ẩm của máy lạnh cửa hàng." },
            { "…Someone… help me…", "…Ai đó… cứu tôi…" },
            { "The SyncPod burns red. The waveform spins — not music.\nLike suction.", "SyncPod cháy đỏ. Sóng âm quay — không phải nhạc.\nNhư lực hút." },
            { "ARRGHH…!", "ARRGHH…!" },
            { "The neon on the wall glitches for one beat — then settles.\nHaruto drops to his knees. One hand clawing at the SyncPod. It won’t come off.", "Neon trên tường nhiễu một nhịp — rồi ổn lại.\nHaruto quỳ xuống. Một tay cào SyncPod. Không gỡ ra được." },
            { "Help… —", "Cứu… —" },
            { "The whine cuts dead.\nSilence.", "Tiếng rít đứt.\nIm lặng." },
            { "Four hours later", "Bốn giờ sau" },
            { "Yellow tape across the mouth of the lane.\nA patrol car. Two people.", "Băng vàng chắn miệng hẻm.\nMột xe tuần tra. Hai người." },
            { "Inspector Lin… how many is this now?", "Thanh tra Lin… đây là vụ thứ mấy rồi?" },
            { "Don’t count. Counting just makes it worse.", "Đừng đếm. Đếm chỉ làm mọi thứ tệ hơn." },
            { "Male victim. Mid-to-late twenties.\nFace-down. One hand reaching toward his ear.", "Nạn nhân nam. Độ hai mươi lăm đến ba mươi.\nNằm sấp. Một tay vẫn với lên tai." },
            { "His skin…", "Da anh ấy…" },
            { "Like a husk. Like something drank him dry from the inside.", "Như cái vỏ khô. Như có thứ đã uống cạn anh từ bên trong." },
            { "Overdose? Or the same as the others?", "Quá liều? Hay giống những người kia?" },
            { "…", "…" },
            { "SyncPod SP-01. Red LED — a crack down the glass.", "SyncPod SP-01. LED đỏ — một vết nứt trên kính." },
            { "What was he listening to before he died?", "Trước khi chết, anh ấy đang nghe gì?" },
            { "Chorus Board logged the device online at 23:51.\nPersonal playlist: indie.\nBut the last entry…", "Chorus Board ghi thiết bị online lúc 23:51.\nPlaylist riêng: indie.\nNhưng mục cuối…" },
            { "Mei Lin opens her tablet. The screen stays angled away from the player.", "Mei Lin mở máy tính bảng. Màn hình vẫn nghiêng khỏi người chơi." },
            { "…a track that isn’t in the public catalog.\nID: SW-ES-040", "…một bài không có trong danh mục công khai.\nID: SW-ES-040" },
            { "SW is…", "SW là…" },
            { "StellaWorks. Guesswork only. Don’t put it in the report.", "StellaWorks. Chỉ là phỏng đoán. Đừng ghi vào báo cáo." },
            { "Why not, Inspector?", "Sao không, thanh tra?" },
            { "Because a report with that name vanishes before it can ever be filed.\nSame as the three before this.", "Vì báo cáo mang cái tên đó biến mất trước khi kịp nộp.\nGiống ba vụ trước." },
            { "Damn it… so what do we do?", "Chết tiệt… thế thì làm sao đây?" },
            { "….", "…." },
            { "From the mouth of the lane, the Eternal Spark hook still carries — thin, far, innocent.", "Từ miệng hẻm, điệp khúc Eternal Spark vẫn vọng tới — mỏng, xa, vô tội." },
            { "Inspector…", "Thanh tra…" },
            { "Do your job.\nAnd hope this time it doesn’t happen to you.", "Làm việc của cậu đi.\nVà cầu là lần này nó đừng tìm đến cậu." },
            { "…If you ever hear something strange in your ears…\nSave yourself first.", "…Nếu cậu nghe thấy thứ lạ trong tai…\nCứu lấy mình trước đã." },
            { "AT LUMINA SQUARE", "QUẢNG TRƯỜNG LUMINA" },
            { "Across the city — Lumina Square.\nRain sheets the crossing. Neon sings on wet asphalt.", "Phía bên kia thành phố — Quảng trường Lumina.\nMưa quét ngã tư. Neon hát trên nhựa đường ướt." },
            { "A SyncPod on Ren’s ear. Blue LED.\nOne pulse — then the track cuts out.", "SyncPod trên tai Ren. LED xanh.\nMột nhịp — rồi bài nhạc cắt." },
            { "Mandatory broadcast window.\nCurrent Chorus Board #1: Eternal Spark — LUXE.", "Khung phát sóng bắt buộc.\nChorus Board hạng 1 hiện tại: Eternal Spark — LUXE." },
            { "…This one again.", "…Lại bài này." },
            { "He keeps walking under the rain, letting the song fill him.", "Cậu tiếp tục đi trong mưa, để bài hát lấp đầy mình." },
            { "If it’s number one, you listen. That’s how this city works.", "Số một thì phải nghe. Thành phố này vận hành như vậy." },
            { "Around him, mouths hum the hook without looking at the billboards.\nRen hears it with them — clear, clean, on the beat.", "Xung quanh, miệng người ta ngân điệp khúc mà không nhìn biển quảng cáo.\nRen nghe cùng họ — rõ, sạch, đúng nhịp." },
            { "No pain. No tug on his feet.\nJust a hit song… and a newcomer to Lumina.", "Không đau. Không có lực kéo ở chân.\nChỉ một bài hit… và một người mới đến Lumina." },
            { "Bag on his shoulder. Early-enrollment papers for HIMA.\nLight rain still falling.", "Túi trên vai. Hồ sơ nhập học sớm của HIMA.\nMưa nhỏ vẫn rơi." },
            { "September 1 — Ren Takahashi arrives in Lumina.", "Ngày 1 tháng 9 — Ren Takahashi đến Lumina." },
            { "THE NEXT MORNING", "SÁNG HÔM SAU" },
            { "Sun cuts across a still-unpacked room.\nEnrollment papers on the desk. Uniform on the hook.", "Nắng cắt qua căn phòng chưa kịp dỡ đồ.\nHồ sơ nhập học trên bàn. Đồng phục trên móc." },
            { "Ren stretches. The city is already loud through the glass.", "Ren duỗi người. Thành phố đã ồn qua lớp kính." },
            { "School kit. Waveform tie. SyncPod on the ear.\nThe mirror does not argue.", "Đồ trường. Cà vạt sóng âm. SyncPod trên tai.\nGương không cãi." },
            { "…Alright. HIMA.", "…Được. HIMA." },
            { "The morning train hangs over the bay.\nEveryone wears the same blue light.", "Tàu sáng treo trên vịnh.\nAi cũng mang cùng một ánh đèn xanh." },
            { "HIMA Music Academy.\nThe banners already know his name as a category: newcomer.", "Học viện Âm nhạc HIMA.\nBiểu ngữ đã xếp tên cậu vào một hạng: người mới." },
            { "Glass corridor. Class 3-2.\nHe turns the corner too fast.", "Hành lang kính. Lớp 3-2.\nCậu quẹo cua quá nhanh." },
            { "Impact.", "Va chạm." },
            { "Hey— watch it!", "Này— coi chừng!" },
            { "Two SyncPods hit the stone. Blue LEDs still pulsing.", "Hai SyncPod rơi xuống đá. LED xanh vẫn nhịp." },
            { "Charlotte picks his up first.\nThe display is still playing.", "Charlotte nhặt máy của cậu trước.\nMàn hình vẫn đang phát." },
            { "Breath of the World…?\nThat isn't on the indie boards.", "Breath of the World…?\nBài này không có trên bảng indie." },
            { "It's mine.", "Của mình." },
            { "…Yours.", "…Của cậu." },
            { "They don't have time to finish it.\nHomeroom is already filling.", "Họ không có thời gian nói hết.\nLớp chủ nhiệm đã đầy người." },
            { "You're in this class too.", "Cậu cũng lớp này à." },
            { "Don't make it weird.", "Đừng làm kỳ cục." },
            { "OPENING CEREMONY", "LỄ KHAI GIẢNG" },
            { "Noon. The hall fills.\nThe principal talks. The city listens.", "Trưa. Hội trường đầy.\nHiệu trưởng nói. Thành phố lắng nghe." },
            { "Then the song in every ear skips — not to silence.\nTo a version that should not exist.", "Rồi bài trong mỗi tai nhảy — không phải sang im lặng.\nSang một phiên bản không được tồn tại." },
            { "That's Eternal Spark. It isn't clean.", "Đó là Eternal Spark. Nó không sạch." },
            { "You hear the undertone too.", "Cậu cũng nghe âm nền." },
            { "The SyncPod on Ren's ear burns red.\nERROR. DESYNC DETECTED.", "SyncPod trên tai Ren cháy đỏ.\nLỖI. PHÁT HIỆN LỆCH NHỊP." },
            { "The floor drops out of the hall.\nRen falls through a spiral of light, hand reaching for a sound that will not let go.", "Sàn hội trường sụp.\nRen rơi qua một vòng xoáy ánh sáng, tay với tới một âm thanh không buông." },
            { "White stone. Broken arches. Banners hanging in a sky that is not a sky.\nThe same wrong note is still in the air.", "Đá trắng. Vòm gãy. Biểu ngữ treo trên bầu trời không phải bầu trời.\nNốt sai ấy vẫn còn trong không khí." },
            { "Where is this?\nThe sound here is exactly the error I heard before.", "Đây là đâu?\nÂm thanh ở đây đúng là lỗi mình nghe lúc nãy." },
            { "The arches shudder.\nSomeone steps out of the light, already moving.", "Những vòm rung.\nAi đó bước ra khỏi ánh sáng, đã chuyển động." },
            { "Why isn't this one under control?\nHe hasn't even changed. I'll hit him and find out.", "Sao tên này chưa bị khống chế?\nHắn còn chưa biến đổi. Mình sẽ đánh rồi biết." },
            { "She lunges.\nA column of light cuts in front of Ren.", "Cô lao tới.\nMột cột sáng chặn trước mặt Ren." },
            { "Stay behind the light.", "Đứng sau ánh sáng." },
            { "Who are you?", "Cậu là ai?" },
            { "Coda. I'll cover you in this fight.", "Coda. Trận này mình che cho cậu." },
            { "Kiki is thrown clear of the arch.\nThe Cadence is splitting along the banners.", "Kiki bị hất khỏi vòm.\nCadence đang nứt theo những biểu ngữ." },
            { "The hall. We run before this place closes.", "Hội trường. Chúng ta chạy trước khi nơi này khép." },
            { "Stay with me. The way out is still open.", "Đi cùng mình. Lối ra vẫn mở." },
            { "They run. The white stone peels away.\nThe ceremony hall rushes back in, loud and ordinary.", "Họ chạy. Đá trắng bong ra.\nHội trường lễ đổ ùa trở lại, ồn và bình thường." },
            { "Of course — let me see what we can do for you.", "Được chứ — để tôi xem chúng tôi làm được gì cho quý khách." },
            { "Ren, what would you recommend?", "Ren, cậu đề xuất gì?" },
            { "Thank you so much — they're perfect!", "Cảm ơn nhiều — chúng hoàn hảo!" },
            { "...I see. I was hoping for something different.", "...Tôi hiểu. Tôi mong một thứ khác." },
            { "I'd like flowers for something special…", "Tôi muốn hoa cho một dịp đặc biệt…" },
            { "Which flowers fit the request?", "Loài hoa nào hợp với yêu cầu?" },
            { "Perfect match. The customer looks delighted.", "Khớp hoàn hảo. Khách trông rất vui." },
            { "Not quite. Remember the request next time.", "Chưa đúng. Lần sau nhớ yêu cầu." },
            { "…That worked.", "…Được rồi." },
            { "I'll remember that.", "Mình sẽ nhớ." },
            { "Morning. I'll give it everything I've got.", "Chào buổi sáng. Mình sẽ cố hết sức." },
            { "Scarlet roses", "Hồng đỏ thắm" },
            { "White lilies", "Ly trắng" },
            { "Sunflowers", "Hướng dương" },
            { "Bright sunflowers", "Hướng dương rực" },
            { "I want to apologize to someone important… what flower says 'sincere apology'?", "Tôi muốn xin lỗi một người quan trọng… loài hoa nào nói được 'lời xin lỗi chân thành'?" },
            { "Which bouquet fits a sincere apology?", "Bó nào hợp một lời xin lỗi chân thành?" },
            { "White lilies — quiet and sincere. Good call.", "Ly trắng — lặng và thành thật. Chọn đúng." },
            { "That reads too celebratory. White lilies would have been safer.", "Nghe vui quá. Ly trắng sẽ an toàn hơn." },
            { "They'd like flashy flowers with a rich aroma.", "Họ muốn hoa bắt mắt, hương đậm." },
            { "Flashy and fragrant — which do you pick?", "Bắt mắt và thơm — cậu chọn gì?" },
            { "Scented roses", "Hồng có hương" },
            { "Artificial silk blooms", "Hoa lụa giả" },
            { "Cactus arrangement", "Chậu xương rồng" },
            { "Scented roses hit both flash and aroma. Nice.", "Hồng có hương vừa bắt mắt vừa thơm. Được." },
            { "No fragrance there. Scented roses were the brief.", "Không có hương. Yêu cầu là hồng có hương." },
            { "My sister has a piano recital tomorrow. Something encouraging?", "Em gái tôi độc tấu piano ngày mai. Thứ gì động viên được?" },
            { "Encouraging flowers for a recital?", "Hoa động viên cho đêm độc tấu?" },
            { "Pale lavender bouquet", "Bó oải hương nhạt" },
            { "Cactus with spikes", "Xương rồng có gai" },
            { "Wilted stems", "Cành héo" },
            { "Lavender feels calm and proud. She'll feel supported.", "Oải hương vừa tĩnh vừa tự hào. Em ấy sẽ thấy được nâng đỡ." },
            { "Too sharp for stage nerves. Lavender was the gentle pick.", "Quá sắc cho người sắp lên sân khấu. Oải hương mới dịu." },
            { "It's our anniversary tonight. I want roses that feel classic, not cliché.", "Tối nay kỷ niệm ngày cưới. Tôi muốn hồng cổ điển, đừng sáo rỗng." },
            { "Classic anniversary roses — which set fits?", "Hồng kỷ niệm cổ điển — bộ nào hợp?" },
            { "Deep red roses", "Hồng đỏ đậm" },
            { "Artificial tulips", "Tulip giả" },
            { "Single daisy", "Một cúc họa mi" },
            { "Deep red roses — timeless. She'll love them.", "Hồng đỏ đậm — không lỗi thời. Cô ấy sẽ thích." },
            { "Too playful for an anniversary. Deep red roses were the mark.", "Quá đùa cho ngày kỷ niệm. Hồng đỏ đậm mới đúng." },
            { "A friend is recovering at home. Something gentle would help.", "Bạn tôi đang dưỡng ở nhà. Thứ dịu sẽ có ích." },
            { "Gentle get-well flowers?", "Hoa thăm bệnh cho dịu?" },
            { "Soft pastel carnations", "Cẩm chướng pastel mềm" },
            { "Thorny cactus", "Xương rồng gai" },
            { "All-black wrap", "Gói toàn đen" },
            { "Pastel carnations feel gentle. The customer smiles.", "Cẩm chướng pastel dịu. Khách mỉm cười." },
            { "Too harsh for recovery. Pastel carnations next time.", "Quá gắt cho người đang dưỡng. Lần sau là cẩm chướng pastel." },
            { "It's my mom's birthday. I saved up — what should I get her?", "Sinh nhật mẹ tôi. Tôi dành dụm — nên tặng gì?" },
            { "A kid's budget — what's the best pick for Mom?", "Túi tiền của trẻ — món nào hợp nhất cho mẹ?" },
            { "Pink carnation bunch", "Bó cẩm chướng hồng" },
            { "Black roses", "Hồng đen" },
            { "Empty vase", "Bình rỗng" },
            { "Pink carnations — sweet and within budget. Good heart.", "Cẩm chướng hồng — ngọt và vừa túi. Tốt bụng." },
            { "Too heavy for a kid's gift. Carnations were the kind choice.", "Nặng quá cho quà của trẻ. Cẩm chướng mới phải." },
            { "I need a respectful gift for my teacher. Nothing romantic.", "Tôi cần quà tôn trọng cho thầy cô. Không lãng mạn." },
            { "Respectful, not romantic — your pick?", "Tôn trọng, không lãng mạn — cậu chọn?" },
            { "Red rose bouquet", "Bó hồng đỏ" },
            { "Yellow chrysanthemums", "Cúc vàng" },
            { "Heart-shaped arrangement", "Bó hình trái tim" },
            { "Yellow chrysanthemums feel respectful without romance. Solid.", "Cúc vàng tôn trọng mà không lãng mạn. Ổn." },
            { "That leans romantic. Chrysanthemums were the safer gift.", "Hướng đó nghiêng sang lãng mạn. Cúc mới an toàn." },
            { "I'd like something quiet for a memorial service. Nothing loud.", "Tôi muốn thứ lặng cho lễ tưởng niệm. Đừng ồn." },
            { "Quiet memorial flowers — your recommendation?", "Hoa tưởng niệm lặng — cậu đề xuất gì?" },
            { "White chrysanthemums", "Cúc trắng" },
            { "Neon gerbera mix", "Hỗn hợp gerbera neon" },
            { "Party confetti wrap", "Gói confetti tiệc" },
            { "White chrysanthemums — restrained and respectful.", "Cúc trắng — tiết chế và tôn trọng." },
            { "Too bright for a memorial. White chrysanthemums were right.", "Quá sáng cho lễ tưởng niệm. Cúc trắng mới đúng." },
            { "They're celebrating a promotion tonight. I need something flashy!", "Tối nay họ ăn mừng thăng chức. Tôi cần thứ bắt mắt!" },
            { "What fits a flashy celebration?", "Thứ gì hợp một bữa ăn mừng rực rỡ?" },
            { "Baby's breath only", "Chỉ hoa baby" },
            { "Gerbera mix", "Hỗn hợp gerbera" },
            { "Dried herbs", "Thảo mộc khô" },
            { "Gerbera mix pops under neon. Perfect for a promotion party.", "Gerbera nổi dưới đèn neon. Hợp tiệc thăng chức." },
            { "Too muted. Gerbera mix would've carried the energy.", "Quá trầm. Hỗn hợp gerbera mới đủ khí thế." }
        };

        public static string Lookup(string english)
        {
            if (string.IsNullOrEmpty(english))
            {
                return null;
            }

            return Vi.TryGetValue(english, out var vietnamese) ? vietnamese : null;
        }
    }
}
